{% set name = "topgrade" %}
{% set version = "16.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/topgrade-rs/topgrade/archive/v{{ version }}.tar.gz
  sha256: 9cfcf31db3322f536f0c48d8a75c6750f18762e0ef60eb7446e3d4a0ab60853f

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - topgrade --help

about:
  home: https://github.com/topgrade-rs/topgrade
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Upgrade all the things
  dev_url: https://github.com/topgrade-rs/topgrade

extra:
  recipe-maintainers:
    - danielnachun
