context:
  version: "17.12.2"

package:
  name: topgrade
  version: ${{ version }}

source:
  url: https://github.com/topgrade-rs/topgrade/archive/v${{ version }}.tar.gz
  sha256: 9cffc162b7a4e0bc40379bc05eff44f62ce57c3ac13126b2d310068f138488ca

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - topgrade --help

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Upgrade all the things
  homepage: https://github.com/topgrade-rs/topgrade
  repository: https://github.com/topgrade-rs/topgrade

extra:
  recipe-maintainers:
    - danielnachun
