context:
  version: "16.6.0"

package:
  name: topgrade
  version: ${{ version }}

source:
  url: https://github.com/topgrade-rs/topgrade/archive/v${{ version }}.tar.gz
  sha256: 29b3ef91e171c217c0e1e324e6b49ffcad6a3a867b4f9395ac92776a1f50f858

build:
  number: 1
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - topgrade --help

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Upgrade all the things
  homepage: https://github.com/topgrade-rs/topgrade
  repository: https://github.com/topgrade-rs/topgrade

extra:
  recipe-maintainers:
    - danielnachun
