context:
  version: "17.5.0"

package:
  name: topgrade
  version: ${{ version }}

source:
  url: https://github.com/topgrade-rs/topgrade/archive/v${{ version }}.tar.gz
  sha256: 4cf993e969df4e4726ff39d54c80e16a0e0710428801b8b84141122300109ff5

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - topgrade --help

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Upgrade all the things
  homepage: https://github.com/topgrade-rs/topgrade
  repository: https://github.com/topgrade-rs/topgrade

extra:
  recipe-maintainers:
    - danielnachun
