context:
  version: "16.2.1"

package:
  name: topgrade
  version: ${{ version }}

source:
  url: https://github.com/topgrade-rs/topgrade/archive/v${{ version }}.tar.gz
  sha256: a457ed0be9bb5e598a1e8d9d5c9991466930ecf455dd14a234bf83a7126bc5e4

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - topgrade --help

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Upgrade all the things
  homepage: https://github.com/topgrade-rs/topgrade
  repository: https://github.com/topgrade-rs/topgrade

extra:
  recipe-maintainers:
    - danielnachun
