context:
  version: "17.2.0"

package:
  name: topgrade
  version: ${{ version }}

source:
  url: https://github.com/topgrade-rs/topgrade/archive/v${{ version }}.tar.gz
  sha256: 716fa4ab554bd0185900af466654bfded79e9256f3177cd86083c38497540308

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - topgrade --help

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Upgrade all the things
  homepage: https://github.com/topgrade-rs/topgrade
  repository: https://github.com/topgrade-rs/topgrade

extra:
  recipe-maintainers:
    - danielnachun
